DMACRYS_EXEC = '/home/pb1c12/local/bin/dmacrys'
NEIGHCRYS_EXEC = '/home/pb1c12/local/bin/neighcrys'
GDMA_EXEC = '/home/pb1c12/local/bin/gdma'
GAUSSIAN_EXEC = '/home/pb1c12/scripts/g09stdin'
COMPACK_EXEC = '/home/jec1f12/compack_1_1/bin/compack'
